language = "typescript" # Must be typescript or python
description = ""
post_install_print = """
ğŸ“‚ Go to your project directory:
	$ cd {project_dir}

ğŸ“¦ Install Dependencies:
        $ npm install

ğŸ› ï¸ Start dev server:
	$ moose dev

ğŸƒ Run your workflows:
	$ moose workflow run military_aircraft_tracking
"""
