[metadata]
Language = "typescript" # Must be typescript or python
Description = ""

[CLI Info]
CLI-Print = """
ğŸ“‚ Go to your project directory:
	$ cd aircraft

ğŸ“¦ Install Dependencies:
    $ npm install

ğŸ› ï¸ Start dev server:
	$ moose dev

ğŸƒRun your workflows:
	$ moose workflow run military_aircraft_tracking
"""