language = "typescript" # Must be typescript or python
description = "Real-time aircraft transponder data."
post_install_print = """
ğŸ“‚ Go to your project directory:
    $ cd {project_dir}

ğŸ“¦ Install Dependencies:
    $ npm install

ğŸ› ï¸ Start dev server:
    $ moose dev
"""
default_sloan_telemetry="comprehensive"
visible=true
