language = "python" # Must be typescript or python
description = "default python project"
post_install_print = """
ğŸ“‚ Go to your project directory:
	$ cd {project_dir}

ğŸ“¦ Install Dependencies:
	$ pip install -r ./requirements.txt

ğŸ› ï¸ Start Moose Server:
	$ moose dev
"""