language = "python" # Must be typescript or python
description = "Empty python project."
post_install_print = """
Deploy on Boreal

The easiest way to deploy your MooseStack Applications is to use Boreal
from the creators of MooseStack.

https://boreal.cloud

---------------------------------------------------------

ğŸ“‚ Go to your project directory:
    $ cd {project_dir}

ğŸ¥„ Create a virtual environment (optional, recommended):
    $ python3 -m venv .venv
    $ source .venv/bin/activate

ğŸ“¦ Install Dependencies:
    $ pip install -r ./requirements.txt

ğŸ› ï¸ Start dev server:
    $ moose dev
"""
default_sloan_telemetry="standard"
