language = "python" # Must be typescript or python
description = "default python project"
post_install_print = """
ğŸ“‚ Go to your project directory:
    $ cd {project_dir}

ğŸ¥„ Create a virtual environment (optional, recommended):
    $ python3 -m venv .venv
    $ source .venv/bin/activate

ğŸ“¦ Install Dependencies:
    $ pip install -r ./requirements.txt

ğŸ› ï¸ Start dev server:
    $ moose dev
"""