language = "typescript" # Must be typescript or python
description = "A brainwave capture and analysis system"
post_install_print = """
Deploy on Boreal

The easiest way to deploy your MooseStack Applications is to use Boreal
from the creators of MooseStack.

https://boreal.cloud

---------------------------------------------------------

This is a MooseStack application for working with Brainwave Data.

To get started, follow these steps:

ğŸ“‚ Go to your project directory:
    $ cd {project_dir}/apps/brainmoose

ğŸ“¦ Install Dependencies:
    $ npm install

ğŸ› ï¸ Start dev server:
    $ moose dev
"""
default_sloan_telemetry="comprehensive"
