[package]
name = "igloo-cli"
version = "0.0.1"
edition = "2021"
description = "Build tool for igloo apps"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = { version = "0.10", features = ["vendored"] }
clap = { version = "4.3.17", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
console = "0.15.7"
dialoguer = "0.10.4"
reqwest = "0.11.18"
hyper = { version = "0.14", features = ["full"] }