[package]
name = "igloo"
version = "0.0.1"
edition = "2021"
description = "Build tool for igloo apps"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.17", features = ["derive"] }
console = "0.15.7"
dialoguer = "0.10.4"
reqwest = "0.11.18"
