language = "typescript" # Must be typescript or python
description = "Real-time aircraft transponder data. Error in data model sends data to a DLQ (this is intentional)."
post_install_print = """
Deploy on Boreal

The easiest way to deploy your Moose app is to use Boreal
from the creators of MooseStack.

https://boreal.cloud

---------------------------------------------------------

ğŸ“‚ Go to your project directory:
    $ cd {project_dir}

ğŸ“¦ Install Dependencies:
    $ npm install

ğŸ› ï¸ Start dev server:
    $ moose dev
"""
default_sloan_telemetry="comprehensive"
visible=false
