language = "typescript" # Must be typescript or python
description = "A template ingesting goodreads data from Kaggle"
post_install_print = """
ğŸ“‚ Go to your project directory:
	$ cd {project_dir}

ğŸ“¦ Install Dependencies:
    $ npm install

ğŸ› ï¸ Start dev server:
	$ moose dev

ğŸ”‘ Add your Kaggle credentials, kaggle.json to ~/.kaggle/kaggle.json per the Kaggle SDK instructions. 
    If you don't have those credentials, see https://www.kaggle.com/docs/api.

ğŸƒâ€â™‚ï¸ Run python ingest script
    $ pip install -r get_data/requirements.txt
    $ python get_data/ingest_goodreads_data.py
"""

# we might need to add python dependencies install file