language = "typescript" # Must be typescript or python
description = "A real-time look at top trending topics on GitHub. Collects & analyzes Star Events from the public events feed"
post_install_print = """

ğŸ“‚ Go to your project directory:
	$ cd {project_dir}/moose-backend

ğŸ“¦ Install Dependencies:
    $ npm install

ğŸ› ï¸ Start dev server:
	$ moose dev
"""