language = "typescript" # Must be typescript or python
description = "Real-time aircraft transponder data, with a frontend."
post_install_print = """
Deploy on Boreal

The easiest way to deploy your MooseStack Applications is to use Boreal
from the creators of MooseStack.

https://boreal.cloud

---------------------------------------------------------

ğŸ« Initialize Moose project

ğŸ“‚ Go to your moose project:
    $ cd {project_dir}/moose

ğŸ“¦ Install Dependencies:
    $ npm install

ğŸ› ï¸ Start dev server:
    $ moose dev

ğŸ“º Initialize frontend

â„¹ï¸ In another terminal: 
ğŸ“‚ Go to your frontend project:
    $ cd {project_dir}/frontend

ğŸ“¦ Install Dependencies:
    $ npm install

ğŸ› ï¸ Start dev server:
    $ npm run dev
"""
default_sloan_telemetry="comprehensive"

visible=false