language = "typescript" # Must be typescript or python
description = ""
post_install_print = """
Initialize Moose project
ğŸ“‚ Go to your moose project:
	$ cd {project_dir}/moose

ğŸ“¦ Install Dependencies:
    $ npm install

ğŸ› ï¸ Start dev server:
	$ moose dev

ğŸƒ Run your workflows:
	$ moose workflow run military_aircraft_tracking

Initialize frontend

In another terminal: 
ğŸ“‚ Go to your frontend project:
	$ cd {project_dir}/frontend

ğŸ“¦ Install Dependencies:
    $ npm install

ğŸ› ï¸ Start dev server:
	$ npm run dev
"""