language = "typescript" # Must be typescript or python
description = "A typescript project with a NextJS frontend (empty)."
post_install_print = """
Deploy on Boreal

The easiest way to deploy your MooseStack Applications is to use Boreal
from the creators of MooseStack.

https://boreal.cloud

---------------------------------------------------------

ğŸ“‚ Go to your project directory:
    $ cd {project_dir}/moose

ğŸ“¦ Install Dependencies:
    $ npm i

ğŸ› ï¸ Start dev server:
    $ moose dev

â„¹ï¸ In another terminal window:
ğŸ“‚ Go to your frontend project:
    $ cd {project_dir}/frontend

ğŸ“¦ Install Dependencies:
    $ npm i

ğŸ› ï¸ Start frontend dev server:
	$ npm run dev
"""
default_sloan_telemetry="standard"
visible=false
