language = "typescript" # Must be typescript or python
description = ""
post_install_print = """
ğŸ“‚ Go to your project directory:
    $ cd {project_dir}/moose

ğŸ“¦ Install Dependencies:
    $ npm i

ğŸ› ï¸ Start dev server:
    $ moose dev

â„¹ï¸ In another terminal window:
ğŸ“‚ Go to your frontend project:
    $ cd {project_dir}/frontend

ğŸ“¦ Install Dependencies:
    $ npm i

ğŸ› ï¸ Start frontend dev server:
	$ npm run dev
"""