language = "Typescript"

[redpanda_config]
broker = "localhost:19092"
message_timeout_ms = 1000
retention_ms = 21600000

[clickhouse_config]
db_name = "local"
user = "panda"
password = "pandapass"
use_ssl = false
host = "localhost"
host_port = 18123
postgres_port = 9005
kafka_port = 9092

[http_server_config]
host = "localhost"
port = 4000

[console_config]
host_port = 3001

[supported_old_versions]
"0.0" = "1fe7b86"
"0.1" = "005108e"
"0.2" = "969a0b7"
"0.3" = "22d9fcb"
"0.4" = "4c49824"
