language = "Typescript"

[redpanda_config]
broker = "localhost:19092"
message_timeout_ms = 1000
retention_ms = 30000

[clickhouse_config]
db_name = "local"
user = "panda"
password = "pandapass"
use_ssl = false
host = "localhost"
host_port = 18123
postgres_port = 9005
kafka_port = 9092

[http_server_config]
host = "localhost"
port = 4000

[console_config]
host_port = 3001

[supported_old_versions]
"0.0" = "8b2ea07"